[package]
name = "XDecrypt"
version = "0.1.0"
authors = ["RabbitMask"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto = "^0.2"
base64 = "0.12.1"
hex = "0.4.2"